### ISSUE TITLE
Duplicate request reported for CSS loaded via LoadCSS

### ISSUE THREAD

**Issue by luboskmetko** [macbre/phantomas#638] opened 2016-05-19 07:15 UTC
When CSS is loaded via https://github.com/filamentgroup/loadCSS, it's reported as a duplicate request, please see https://github.com/gmetais/YellowLabTools/issues/156

**Comment by macbre** [comment] 2017-06-03 12:41
Closing as @gmetais is unable to reproduce this issue (see https://github.com/gmetais/YellowLabTools/issues/156)

**Closed by macbre** 2017-06-03 12:41 UTC
Labels: bug, research

**Comment by gmetais** [comment] 2017-06-03 17:56
Oops sorry, I forgot to tell you!
